### PR TITLE
Merging branches

### PR DESCRIPTION
**Pull request by yoyopower**
Using this to merge the branches

### CODE REVIEW

**Comment by yoyopower** [comment]
@RandomHashTags you will need to create a new component for your code, after that I will merge these.

**Comment by RandomHashTags** [comment]
I'm not going to code with yoyo if he just removed my code and replaces it
with trash code.

**Comment by yoyopower** [comment]
@RandomHashTags you do realise this is a separate branch? Your code is still on the master branch, it just needs to be added to this branch.

**Comment by RandomHashTags** [comment]
Yeah, but he made a main class, with poorly made events, command executors,
and config files. When we merge them together, we can only have 1 of the
main classes, and 1 of the events.

**Comment by yoyopower** [comment]
Want to elaborate there pal? Instead of blowing up try a productive chat.

**Comment by RandomHashTags** [comment]
It'll go down in discord chat

**Pull request merged**
